<?php
namespace api\controllers;

use Yii;
use yii\rest\ActiveController;


/**
 * AdminController implements the CRUD actions for Admin model.
 */
class AdminController extends  ActiveController
{
    public $modelClass = "backend\models\Admin";
    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
    }

    public function actionIndex()
    {

//            var_dump(Yii::$app->request->get());
      echo "";die;
    }









}
